name: Build and deploy to Azure Spring Cloud

on:
  push:
    branches: xstof

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      working-directory: ./solutionfolder/weather-service
      run: mvn package -DskipTests
    - name: Login to Azure Spring Cloud
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Azure Spring Cloud extension
      run: az extension add -y --name spring-cloud
    - name: Deploy to Azure Spring Cloud
      run: az spring-cloud app deploy --resource-group tutorial-asc --service gitteasc --name weather-service --jar-path target/demo-0.0.1-SNAPSHOT.jar
      working-directory: ./solutionfolder/weather-service